Fixed build issue by generating DiscoveryTask default destructor
Setting ~DiscoveryTask virtual will make compiler generate actual code
instead of inlining by default.

This prevents link issues (where code can't be inlined?)

Problem was observed while building using tizen-sdk :

    libresource_hosting.so: undefined reference to \
    `OIC::Service::RCSDiscoveryManager::DiscoveryTask::~DiscoveryTask()'

Used toochain on Tizen:2.4:Mobile is arm-linux-gnueabi-g++ (GCC) 4.9.2

Change-Id: I708812404b01c35f09e8aa68afad962c7d6e0df3
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>