yocto: Use LDFLAGS if defined in build environment
Without this change, extra flags like "--hash-style=gnu"
 will be ignored and quality checks will fail.

Reported message is:
  ERROR: iotivity-* do_package_qa: QA Issue:
  No GNU_HASH in the elf binary:
  '*/samples/opt/iotivity/examples/plugins/zigbee/iotivityandzigbeeserver'
  (...)
  ERROR: iotivity-* do_package_qa: QA run found fatal errors. Please consider fixing them.
  ERROR: iotivity-* do_package_qa: Function failed: do_package_qa
  (...)
  Summary: There were 8 ERROR messages shown, returning a non-zero exit code.

Bug: https://lists.yoctoproject.org/pipermail/yocto/2016-August/031442.html
Bug-AGL: https://jira.automotivelinux.org/browse/SPEC-158
Change-Id: Ifa240817c768df3a7d154d36b699de8ca0f0307a
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/11073
Reviewed-by: Kishen Maloor <kishen.maloor@intel.com>
Reviewed-by: Ziran Sun <ziran.sun@samsung.com>
Reviewed-by: Dave Thaler <dthaler@microsoft.com>
Tested-by: Dave Thaler <dthaler@microsoft.com>
(cherry picked from commit 82c95d3ba9fb607980981dfb56e8bd9515609454)