WIP: build: Add docker file to build on fedora
This is useful for ARTIK7

Note scons is reinstalled to workaround this issue,
observed on scons-2.4.1-1.fc24 on Fedora 23 for ARTIK7:

  scons install (...)
  scons: Building targets ...
  Install file: ".../iotivity_config.h" as "..."
  (...)
  Install file: ".../libconnectivity_abstraction.a" as ".../usr/lib64/libconnectivity_abstraction.a"
  scons: *** [.../release/liblogger.a] AttributeError : 'FileBuildInfo' object has no attribute 'result'
  scons: building terminated because of errors.

Bug: https://jira.iotivity.org/browse/IOT-2668
Change-Id: I4a4157a0fc68ab984342447f1862ce4592f1accb
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>