resource: Include functional header for g++-7.1.0
It was tested on yocto poky master on iotivity-1.2.1 (and later):

  resource/include/OCUtilities.h: \
  In function 'OCStackResult OC::nil_guard(PtrT&&, FnT&&, ParamTs&& ...)':
  resource/include/OCUtilities.h:85:21: \
  error: 'bind' is not a member of 'std'
  return std::bind(fn, p, std::ref(params)...)();

  resource/include/OCApi.h: At global scope:
  resource/include/OCApi.h:362:18: \
  error: 'function' in namespace 'std' does not name a template type
  typedef std::function<void(std::shared_ptr<OCResource>)> FindCallback;

Change-Id: Ie1cab497c33fde394f77490a1d636eb36a563396
Origin: https://gerrit.iotivity.org/gerrit/#/c/21069/
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
Reviewed-on: https://gerrit.iotivity.org/gerrit/21067
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>
Tested-by: jenkins-iotivity <jenkins@iotivity.org>
(cherry picked from commit 26c2798188497da22e0a70efebc47991dd755db2)
Reviewed-on: https://gerrit.iotivity.org/gerrit/21065
Reviewed-by: Dan Mihai <Daniel.Mihai@microsoft.com>
Reviewed-by: George Nash <george.nash@intel.com>
Reviewed-by: Rick Bell <richard.s.bell@intel.com>